# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# If not running interactively, don't do anything
case $- in
  *i*) ;;
    *) return;;
esac

export PATH="$PATH:$HOME/bin:$HOME/.local/bin" # Add a local place to put binaries so I don't have to pollute root

source ~/bashrc/shell.sh
source ~/bashrc/unix.sh
#source ~/bashrc/ruby.sh
source ~/bashrc/rust.sh
source ~/bashrc/go.sh
source ~/bashrc/python.sh
#source ~/bashrc/node.sh
source ~/bashrc/git-completion.bash
source ~/bashrc/alias.sh
source ~/bashrc/chime.sh
source ~/bashrc/prompt.sh
source ~/bashrc/local.sh

#script screen.log


. "$HOME/.cargo/env"
